simulation:
  time_step: 3  
  total_time: 7200  

od_demand:
  - origin: "Node A"
    destination: "Node D"
    start_time: 0
    end_time: 3600
    rate: 4600  
  - origin: "Node A"
    destination: "Node E"
    start_time: 0
    end_time: 1800
    rate: 500  
  - origin: "Node A"
    destination: "Node E"
    start_time: 1800
    end_time: 3600
    rate: 600 
  - origin: "Node F"
    destination: "Node D"
    start_time: 0
    end_time: 3600
    rate: 900  
  - origin: "Node F"
    destination: "Node D"
    start_time: 3600
    end_time: 5400
    rate: 800

meter_schedule:
  - node: "Node G"
    start_time: 230
    end_time: 3900
    rate: 800  
  
nodes:
  - id: "Node A"
    type: "source"
  - id: "Node B"
    type: "diverge"
  - id: "Node C"
    type: "merge"
  - id: "Node D"
    type: "sink"
  - id: "Node E"
    type: "sink"
  - id: "Node F"
    type: "source"
  - id: "Node G"
    type: "meter"

edges:
  - id: "SegAB"
    source: "Node A"
    target: "Node B"
    length: 3.0 
    lanes: 3
    v: 60 
    q_max: 1800 
    k_jam: 120 

  - id: "SegBE"
    source: "Node B"
    target: "Node E"
    length: 0.1 
    lanes: 1
    v: 60
    q_max: 1800
    k_jam: 120

  - id: "SegBC"
    source: "Node B"
    target: "Node C"
    length: 1.0 
    lanes: 3
    v: 60
    q_max: 1800
    k_jam: 120
    merge_weight: 2.5  

  - id: "SegFG"
    source: "Node F"
    target: "Node G" 
    length: 0.25 
    lanes: 1
    v: 60
    q_max: 1800
    k_jam: 120

  - id: "SegGC" 
    source: "Node G"
    target: "Node C"
    length: 0.1 
    lanes: 1
    v: 60
    q_max: 1800
    k_jam: 120
    merge_weight: 0.5  

  - id: "SegCD"
    source: "Node C"
    target: "Node D"
    length: 2.0 
    lanes: 3
    v: 60
    q_max: 1800
    k_jam: 120