import unittest
import yaml
import os
import numpy as np

from cell_transmission_model import CTMNetwork

class TestIntegrationSingleLinkFlow(unittest.TestCase):
    def setUp(self):
        """
        Create a custom, simple network_config.yaml file with a single link.
        """
        self.test_config_path = "temp_single_link_config.yaml"
        self.config = {
            "simulation": {
                "time_step": 10,  # 10 seconds
                "total_time": 60  # 1 minute of simulation (6 steps)
            },
            "od_demand": [], # We will manually inject demand for precise testing
            "nodes": [
                {"id": "START", "type": "source"},
                {"id": "END", "type": "sink"}
            ],
            "edges": [
                {
                    "id": "single_link",
                    "source": "START",
                    "target": "END",
                    "length": 1.0, # 1 mile
                    "lanes": 1,
                    "v": 60,
                    "q_max": 2000,
                    "k_jam": 150
                }
            ]
        }
        
        # Write the temporary config file
        with open(self.test_config_path, 'w') as f:
            yaml.dump(self.config, f)

    def tearDown(self):
        """
        Clean up the temporary configuration and generated output files after the test.
        """
        if os.path.exists(self.test_config_path):
            os.remove(self.test_config_path)
            
        # Clean up the output excel file generated by collect_history_and_post_process
        if os.path.exists("ctm_matrices_output.xlsx"):
            os.remove("ctm_matrices_output.xlsx")

    def test_single_vehicle_propagation(self):
        """
        Evaluate if a single vehicle injected at the source properly updates 
        the transfer (y) and accumulation (n) matrices across the 3rd destination axis.
        """
        print("\n--- Running Integration Test: Single Vehicle Propagation ---")
        
        # Initialize network with the temporary config
        net = CTMNetwork(self.test_config_path)
        
        # Manually inject exactly 1 vehicle into the source queue at time step 0 for dest index 0
        net.nodes_state["START"].queue[0, 0] = 1.0
        
        # Run simulation
        net.run()
        
        n_matrix = net.edges_state["single_link"].n
        y_matrix = net.edges_state["single_link"].y

        # --- Assertions to verify the logic ---
        
        # 1. Ensure the transfer matrix is not entirely empty
        self.assertTrue(
            np.any(y_matrix > 0), 
            "The transfer matrix (y) is completely empty. Vehicles did not enter."
        )
        
        # 2. Ensure the accumulation matrix is not entirely empty
        self.assertTrue(
            np.any(n_matrix > 0), 
            "The accumulation matrix (n) is completely empty."
        )
        
        # 3. Check specific cell propagation for the first step on the destination 0 axis
        self.assertEqual(
            y_matrix[0, 0, 0], 1.0, 
            "Expected exactly 1 vehicle to transfer from the source queue into the first cell at step 0."
        )
        
        self.assertEqual(
            n_matrix[1, 0, 0], 1.0, 
            "Expected the 1 vehicle to accumulate in the first cell by step 1."
        )
        
        print("--- Integration Test Complete ---")

    def test_large_demand_capacity_constraint(self):
        """
        Evaluate if a very large demand is properly bounded by the 
        receiving capacity (Q) of the cells as it propagates forward.
        """
        print("\n--- Running Integration Test: Large Demand Capacity Constraint ---")
        
        # Initialize network with the temporary config
        net = CTMNetwork(self.test_config_path)
        
        # Manually inject a massive demand (1000 vehicles) into the source queue
        net.nodes_state["START"].queue[0, 0] = 1000.0
        
        # Run simulation
        net.run()
        
        n_matrix = net.edges_state["single_link"].n
        y_matrix = net.edges_state["single_link"].y
        
        # Calculate expected Q (capacity per time step)
        # q_max = 2000 veh/hr, lanes = 1, dt = 10s
        expected_q = 2000 * 1 * (10 / 3600.0) # approx 5.5555... vehicles per time step
        
        # 1. Flow from source into cell 0 at step 0 should be bounded by Q
        self.assertAlmostEqual(
            y_matrix[0, 0, 0], expected_q, places=4, 
            msg=f"Expected flow into first cell to be bounded by Q ({expected_q})."
        )
        
        # 2. Accumulation in cell 0 at step 1 should be exactly Q
        self.assertAlmostEqual(
            n_matrix[1, 0, 0], expected_q, places=4, 
            msg="Expected accumulation in the first cell to equal Q after step 0."
        )
        
        # 3. Flow from cell 0 to cell 1 at step 1 should be exactly Q
        #    (Since cell 0 contains Q, Sending capacity is min(n, Q) = Q)
        self.assertAlmostEqual(
            y_matrix[1, 1, 0], expected_q, places=4, 
            msg="Expected flow propagating to the second cell to be exactly Q."
        )
        
        # 4. Source should continue to pump exactly Q into cell 0 at step 1
        self.assertAlmostEqual(
            y_matrix[1, 0, 0], expected_q, places=4, 
            msg="Expected source to continue injecting exactly Q vehicles into the first cell."
        )
        
        print("--- Integration Test Complete ---")

    def test_discretization_bottleneck(self):
        """
        Evaluate if a cell configuration that does not perfectly divide into
        the ideal cell length (v * dt) properly avoids numerical bottlenecks 
        (e.g., restricting capacity to 2.45 instead of 2.50).
        """
        print("\n--- Running Integration Test: Discretization Bottleneck ---")
        config = {
            "simulation": {"time_step": 6, "total_time": 60},
            "od_demand": [],
            "nodes": [
                {"id": "START", "type": "source"},
                {"id": "END", "type": "sink"}
            ],
            "edges": [
                {
                    "id": "single_link",
                    "source": "START",
                    "target": "END",
                    "length": 0.5, # 0.5 miles at 45 mph is 6.66 cells (rounds to 7 cells)
                    "lanes": 1,
                    "v": 45,
                    "q_max": 1500,
                    "k_jam": 120
                }
            ]
        }
        test_path = "temp_bottleneck_config.yaml"
        with open(test_path, 'w') as f:
            yaml.dump(config, f)
            
        try:
            net = CTMNetwork(test_path)
            
            # Expected exact capacity: 1500 veh/hr * (6s / 3600s) = 2.5 veh/step
            q_max_step = 2.5
            
            # Flood the source queue so it always provides capacity
            net.nodes_state["START"].queue[:, 0] = 100.0
            
            net.run()
            
            n_matrix = net.edges_state["single_link"].n
            y_matrix = net.edges_state["single_link"].y
            
            # By step 4, the first few cells should be completely saturated exactly at q_max_step.
            # If the discretization bottleneck is active, this would wrongly equal ~2.45.
            self.assertAlmostEqual(
                n_matrix[4, 0, 0], q_max_step, places=4,
                msg=f"Discretization bottleneck detected! Expected cell accumulation to be exactly {q_max_step}."
            )
            self.assertAlmostEqual(
                y_matrix[4, 1, 0], q_max_step, places=4,
                msg=f"Discretization bottleneck detected! Expected flow between cells to be exactly {q_max_step}."
            )
        finally:
            if os.path.exists(test_path):
                os.remove(test_path)
                
        print("--- Integration Test Complete ---")

if __name__ == '__main__':
    unittest.main()